FROM alpine:edge

MAINTAINER Chuanjian Wang <me@ckeyer.com>

RUN mkdir -p /opt/0
RUN mkdir -p /opt/1
RUN mkdir -p /opt/2
RUN mkdir -p /opt/3
RUN mkdir -p /opt/4
RUN mkdir -p /opt/5
RUN mkdir -p /opt/6
RUN mkdir -p /opt/7
RUN mkdir -p /opt/8
RUN mkdir -p /opt/9
RUN mkdir -p /opt/10
RUN mkdir -p /opt/11
RUN mkdir -p /opt/12
RUN mkdir -p /opt/13
RUN mkdir -p /opt/14
RUN mkdir -p /opt/15
RUN mkdir -p /opt/16
RUN mkdir -p /opt/17
RUN mkdir -p /opt/18
RUN mkdir -p /opt/19
RUN mkdir -p /opt/20
RUN mkdir -p /opt/21
RUN mkdir -p /opt/22
RUN mkdir -p /opt/23
RUN mkdir -p /opt/24
RUN mkdir -p /opt/25
RUN mkdir -p /opt/26
RUN mkdir -p /opt/27
RUN mkdir -p /opt/28
RUN mkdir -p /opt/29
RUN mkdir -p /opt/30
RUN mkdir -p /opt/31
RUN mkdir -p /opt/32
RUN mkdir -p /opt/33
RUN mkdir -p /opt/34
RUN mkdir -p /opt/35
RUN mkdir -p /opt/36
RUN mkdir -p /opt/37
RUN mkdir -p /opt/38
RUN mkdir -p /opt/39
RUN mkdir -p /opt/40
RUN mkdir -p /opt/41
RUN mkdir -p /opt/42
RUN mkdir -p /opt/43
RUN mkdir -p /opt/44
RUN mkdir -p /opt/45
RUN mkdir -p /opt/46
RUN mkdir -p /opt/47
RUN mkdir -p /opt/48
RUN mkdir -p /opt/49
RUN mkdir -p /opt/50
RUN mkdir -p /opt/51
RUN mkdir -p /opt/52
RUN mkdir -p /opt/53
RUN mkdir -p /opt/54
RUN mkdir -p /opt/55
RUN mkdir -p /opt/56
RUN mkdir -p /opt/57
RUN mkdir -p /opt/58
RUN mkdir -p /opt/59
RUN mkdir -p /opt/60
RUN mkdir -p /opt/61
RUN mkdir -p /opt/62
RUN mkdir -p /opt/63
RUN mkdir -p /opt/64
RUN mkdir -p /opt/65
RUN mkdir -p /opt/66
RUN mkdir -p /opt/67
RUN mkdir -p /opt/68
RUN mkdir -p /opt/69
RUN mkdir -p /opt/70
RUN mkdir -p /opt/71
RUN mkdir -p /opt/72
RUN mkdir -p /opt/73
RUN mkdir -p /opt/74
RUN mkdir -p /opt/75
RUN mkdir -p /opt/76
RUN mkdir -p /opt/77
RUN mkdir -p /opt/78
RUN mkdir -p /opt/79
RUN mkdir -p /opt/80
RUN mkdir -p /opt/81
RUN mkdir -p /opt/82
RUN mkdir -p /opt/83
RUN mkdir -p /opt/84
RUN mkdir -p /opt/85
RUN mkdir -p /opt/86
RUN mkdir -p /opt/87
RUN mkdir -p /opt/88
RUN mkdir -p /opt/89
RUN mkdir -p /opt/90
RUN mkdir -p /opt/91
RUN mkdir -p /opt/92
RUN mkdir -p /opt/93
RUN mkdir -p /opt/94
RUN mkdir -p /opt/95
RUN mkdir -p /opt/96
RUN mkdir -p /opt/97
RUN mkdir -p /opt/98
RUN mkdir -p /opt/99
RUN mkdir -p /opt/100
RUN mkdir -p /opt/101
RUN mkdir -p /opt/102
RUN mkdir -p /opt/103
RUN mkdir -p /opt/104
RUN mkdir -p /opt/105
RUN mkdir -p /opt/106
RUN mkdir -p /opt/107
RUN mkdir -p /opt/108
RUN mkdir -p /opt/109
RUN mkdir -p /opt/110
RUN mkdir -p /opt/111
RUN mkdir -p /opt/112
RUN mkdir -p /opt/113
RUN mkdir -p /opt/114
RUN mkdir -p /opt/115
RUN mkdir -p /opt/116
RUN mkdir -p /opt/117
RUN mkdir -p /opt/118
RUN mkdir -p /opt/119
RUN mkdir -p /opt/120
RUN mkdir -p /opt/121
RUN mkdir -p /opt/122
